services:
  nextcloud:
    image: nextcloud:apache
    environment:
      # Configurações para RDS - substitua pelos valores do seu RDS
      - POSTGRES_HOST=nextcloud.c29gca8kizzb.us-east-1.rds.amazonaws.com
      - POSTGRES_PASSWORD=k3dCcZE7ybObAgXOgjBO
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PORT=5432
    ports:
      - 80:80
    restart: always
    volumes:
      # Opção 1: Volume local (atual)
      - nc_data:/var/www/html

volumes:
  nc_data: